artifacts_root : artifacts


data_ingestion:
  root_dir : artifacts/data_ingestion
  source_URL : https://github.com/Zeytunzeynep/DataSets/raw/main/churn_dataset.zip
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion


data_validation:
  root_dir : artifacts/data_validation
  status_file : artifacts/status_file.txt
  unzip_dir : artifacts/data_ingestion/data.zip


data_transformation:
  root_dir : artifacts/data_transformation
  data_path: artifacts